logging:
  level:
    '[org.springframework.security]': debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3304/securitydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: myuser
    password: mypassword
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
         
    
          