spring:
  kafka:
    streams:
      bootstrap-servers:
      - "localhost:9092"
      application-id: "kafka-stream"
    consumer:
      group-id: uppercase
  main:
    allow-circular-references: true