server:
  port: 8081
spring:
  datasource:
        url: http://localhost:6379/redisdb
        username:  myuser
        password: mypassword
        driver-class-name:  com.mysql.cj.jdbc.Driver   
  cache:
    type: redis
    redis:
      time-to-live: 100000S
    cache-names:
    - rediscache
    
  jpa:
     show-sql: true
     generate-ddl: true
     properties: 
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect    